ALTER TABLE users
    ADD COLUMN IF NOT EXISTS tag_name VARCHAR(120) NULL,
    ADD COLUMN IF NOT EXISTS discord_tag VARCHAR(120) NULL,
    ADD COLUMN IF NOT EXISTS location VARCHAR(200) NULL,
    ADD COLUMN IF NOT EXISTS interests VARCHAR(500) NULL;
